name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Pull request
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          file: platforms.Dockerfile
          push: false
          tags: |
            dodopizza/mysql-data-mover-platforms:test
            dodopizza/mysql-data-mover-platforms:latest

      - name: Build linux image
        uses: docker/build-push-action@v5
        with:
          file: linux.Dockerfile
          push: false
          tags: |
            dodopizza/mysql-data-mover-platforms:test
            dodopizza/mysql-data-mover-platforms:latest

      - name: Integration test
        timeout-minutes: 10
        run: |
          ./run-integration-tests.sh -t 'test'
