name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Pull request
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Integration test
        timeout-minutes: 10
        run: |
          ./run-integration-tests.sh
