name: Build and test

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          file: verification.Dockerfile
          push: false
          tags: dodopizza/mysql-data-mover:test
