name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set common vars
        id: common_vars
        # Ex:
        #   refs/tags/0.1.12345 -> 0.1.12345
        run: |
          app_version=$( echo ${{ github.ref }} | sed -n 's/refs\/tags\/\(.*\)/\1/p' )
          if [ -z "${app_version}" ]; then exit 1; fi
          echo "app_version: ${app_version}"
          echo "app_version=${app_version}" >> $GITHUB_OUTPUT

      - name: Build for platforms
        uses: docker/build-push-action@v5
        with:
          file: platforms.Dockerfile
          push: false
          tags: dodopizza/mysql-data-mover-platforms:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
          password: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: linux.Dockerfile
          push: true
          tags: dodopizza/mysql-data-mover:${{ steps.common_vars.outputs.app_version }}-linux-x64
